version: '3.8'

services:
  frontend_dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: imyanya-frontend-container
    volumes:
      - .:/imyanya_web_app
      - /imyanya_web_app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    networks:
      - imyanya-network

  frontend_nginx:
    image: nginx:1.24.0-alpine
    container_name: imyanya-frontend-nginx-container
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - imyanya-network
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend_dev

networks:
  imyanya-network:
    name: imyanya-network